# Generated by Django 3.2.3 on 2021-07-29 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChattingApp', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_head1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_head2',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='No name chat', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='My name is ', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='2001-01-01', max_length=12),
        ),
    ]
