# Generated by Django 3.2.3 on 2021-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChattingApp', '0006_auto_20210729_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='My name is ', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2001-01-01', max_length=12),
        ),
    ]
